owner: ophilippot-seren
repo: serenaid-status

sites:
  - name: Serenaid App
    url: https://serenaid.app

  - name: API Health
    url: https://dowgbbuckuxjjuxckemi.supabase.co/functions/v1/serenaid-core/health/ping
    headers:
      - "Authorization: Bearer $SUPABASE_ANON_KEY"

  - name: Database
    url: https://dowgbbuckuxjjuxckemi.supabase.co/functions/v1/serenaid-core/health/db
    headers:
      - "Authorization: Bearer $SUPABASE_ANON_KEY"

  - name: Notification Scheduler
    url: https://dowgbbuckuxjjuxckemi.supabase.co/functions/v1/serenaid-core/health/scheduler
    headers:
      - "Authorization: Bearer $SUPABASE_ANON_KEY"

status-website:
  cname: status.serenaid.app
  name: Serenaid Status
  introTitle: "**Serenaid** est actuellement opérationnel"
  introMessage: Cette page affiche l'état en temps réel de tous les services Serenaid.
  navbar:
    - title: Serenaid
      href: https://serenaid.app

notifications:
  - type: email
    address: contact@serenaid.app

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  updates: "0 0 * * *"
  staticSite: "0 0 * * *"

i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Tous les systèmes sont opérationnels
  incidentReport: "Rapport d'incident pour $site"
